### ISSUE TITLE
[BUG]: western_goods_bind_lighter.script:246: attempt to index local 'obj' (a nil value)

### ISSUE THREAD

**Issue by Jordanbestkz** [nltp-ashes/Western-Goods#78]
### Description

Greetings
Can you help?
The game crashes when trying to buy or spawn a lighter to inventory
i updated mod exces, but game crashes (((
Thank you

### Addon version

v2.6.1

### Game version

1.5.2

### Game execution log

[xray_aziz.log](https://github.com/user-attachments/files/15524648/xray_aziz.log)

### Confirmation

- [X] Yes, I have read the instructions and have all the pre-requisites installed.

**Comment by nltp-ashes** [comment]
Hi @Jordanbestkz,

First, thank you for reporting the issue here and not in ModDB comments or on Discord. I believe it is useful to group troubleshooting in a single place, and GitHub issues are perfect for that.

It seems your issue is similar to [this issue](https://github.com/nltp-ashes/Western-Goods/issues/76), can you look into the [solution we found](https://github.com/nltp-ashes/Western-Goods/issues/76#issuecomment-2132226929) there and see if it helps you?

**Comment by Jordanbestkz** [comment]
Good afternoon. As I wrote earlier, I tried this solution - updated my game executables, but it didnt help.
Can you check logs? Could the problem be something else?

**Comment by Jordanbestkz** [comment]
@nltp-ashes Hi

> other files from the "modded exes" project, 

Are there any other script files that need to be updated?

**Comment by nltp-ashes** [comment]
Hi @Jordanbestkz,

I cannot explain what is happening. There is no way for this bug to happen if you installed the modded exes, unless the "Anomaly Custom" modpack you use goes out of its way to specifically make it so this bit of code from the modded exes doesn't work.

So yeah, I'm sorry, but I cannot help you.

**Comment by Jordanbestkz** [comment]
Good afternoon @nltp-ashes 
Thank you for your attention
I will try to fix the error myself
