### ISSUE TITLE
[FEATURE]: Readables - Add parts to disassemble magazines

### ISSUE THREAD

**Issue by Minolta50** [nltp-ashes/Western-Goods#89]
### Abstract

It would be great to add recipes for disassembling new magazines.

### Importance

3 - Nice but not required

### Description

![nor_parts_list]

wg_porn_mag_1 = prt_i_paper
wg_porn_mag_2 = prt_i_paper
wg_porn_mag_3 = prt_i_paper
wg_xbox_mag_1 = prt_i_paper
wg_xbox_mag_2 = prt_i_paper
wg_strana_igr_mag_1 = prt_i_paper
wg_car_mag_1 = prt_i_paper
wg_car_mag_2 = prt_i_paper

**Comment by nltp-ashes** [comment]
Hi @Minolta50,

Thank you for creating the issue. This will make sure your suggestion is not forgotten about :) It also helps me to track the different things I'm working on.

I'll update this issue when development progresses.

**Comment by nltp-ashes** [comment]
Hello @Minolta50,

Development on your issue was completed. Magazines will now have paper as parts. This will be released in `v3.1.0`.

![image](https://github.com/user-attachments/assets/9463b8d9-8256-4816-8174-2e69202e63b0)

![image](https://github.com/user-attachments/assets/8538463b-16b3-4c3a-91c5-fe08946ebdbb)
